export default {
  ADD_TO_CART_REQUEST: "ADD_TO_CART_REQUEST",
  INCREAMENT_ITEM_REQUEST: "INCREAMENT_ITEM_REQUEST",
  DECREAMENT_ITEM_REQUEST: "DECREAMENT_ITEM_REQUEST",

  REMOVE_ITEM_REQUEST: "REMOVE_ITEM_REQUEST",
  REMOVE_ALL_REQUEST: "REMOVE_ALL_REQUEST",
  CHANGE_QUANTITY_REQUEST: "CHANGE_QUANTITY_REQUEST",
};
